name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取全部提交历史

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/Safeheron/safeheron-api-sdk-go.git
          git fetch upstream

      - name: Merge Upstream
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
